### PR TITLE
Null safety

### PR DESCRIPTION
**Pull request by Mol0ko**
Migration to null safety.
signalr_core package won't migrate to null safety without this package.

@jamiewest  please, check PR

### CODE REVIEW

**Comment by jamiewest** [comment]
Thank you! I will review this evening 🙂

**Comment by jamiewest** [comment]
Did you happen to use the migration tool?

**Comment by Mol0ko** [comment]
Yes I did. I followed [this](https://dart.dev/null-safety/migration-guide) guide and used migration tool.

**Comment by jamiewest** [comment]
Published 0.1.0 to pub.dev, thank you for your contribution!

**Pull request merged**
